import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPFOrder,gatewayConfiguration,gatewayRequirements,submitPFOrder} from '../lib/pf-gateway.mjs';
import {gatewayTestOrderInput} from '../lib/pf-orders.mjs';

const base={messageId:'message-1',createdAt:'2026-09-22T10:00:00.000Z',purchaseOrderNumber:'SMERCH-order-1',currency:'DKK',supplierTotal:280,shipping:{name:'Joakim',email:'joakim@example.dk',phone:'12345678',address:{street:'Testvej 1',postalCode:'1000',city:'København',country:'DK'}},lines:[{sku:'10000200',supplierUnitPrice:10,quantity:25,decorations:[]}]};
const settings={senderId:'SMERCH',communicationEmail:'orders@example.dk'};
test('blank PF order maps shipment and supplier prices without requesting proof',()=>{const payload=buildPFOrder(base,settings);assert.equal(payload.OrderType,'BLANK');assert.equal(payload.SKUs[0].SKUID,'10000200');assert.equal(payload.SKUs[0].UnitPrice,10);assert.equal(payload.SKUs[0].Eproof,undefined);assert.equal(payload.Shipments[0].shipContact.shipAddress.Country,'DK');});
test('decorated PF order requests e-proof and links both artwork files',()=>{const order=structuredClone(base);order.lines[0].decorations=[{methodCode:'4',positionCode:'front',colors:2,pmsColors:['186 C','Black C'],width:80,height:40,text:'Hej',files:{raw:'https://art.example.dk/raw.pdf',proof:'https://art.example.dk/proof.pdf'}}];const payload=buildPFOrder(order,settings);assert.equal(payload.OrderType,'DECORATED');assert.equal(payload.SKUs[0].Eproof,'EPROOF');assert.equal(payload.Decorations[0].ConfigurationID,'4-front');assert.deepEqual(payload.Decorations[0].ArtworkReferenceIDs,['0','1']);assert.deepEqual(payload.Artworks.map(item=>item.ArtworkType),['RAW','PROOF']);assert.throws(()=>buildPFOrder({...order,lines:[{...order.lines[0],decorations:[{...order.lines[0].decorations[0],pmsColors:['186 C']}]}]},settings),/farver/);assert.throws(()=>buildPFOrder({...order,lines:[{...order.lines[0],decorations:[{...order.lines[0].decorations[0],files:{raw:'http://art.example.dk/raw.pdf',proof:'https://art.example.dk/proof.pdf'}}]}]},settings),/HTTPS/);});
test('PF can receive original RAW files and create its own mandatory e-proof',()=>{const order=structuredClone(base);order.lines[0].decorations=[{methodCode:'4',positionCode:'front',colors:1,pmsColors:['Black C'],width:80,height:40,files:{raw:['https://art.example.dk/logo.ai','https://art.example.dk/text.txt']}}];const payload=buildPFOrder(order,settings);assert.equal(payload.SKUs[0].Eproof,'EPROOF');assert.deepEqual(payload.Artworks.map(item=>item.ArtworkType),['RAW','RAW']);assert.deepEqual(payload.Decorations[0].ArtworkReferenceIDs,['0','1']);});
test('live PF endpoint requires a separate explicit enable switch',()=>{assert.deepEqual(gatewayConfiguration({}),{mode:'off',ready:false});assert.throws(()=>gatewayConfiguration({PF_GATEWAY_MODE:'live'}),/Liveordrer/);const config=gatewayConfiguration({PF_GATEWAY_MODE:'test',PF_GATEWAY_USERNAME:'u',PF_GATEWAY_TEST_PASSWORD:'p',PF_GATEWAY_SENDER_ID:'s',PF_COMMUNICATION_EMAIL:'x@y.dk'});assert.equal(config.ready,true);assert.match(config.endpoint,/\/test\//);});
test('Gateway status explains missing PF access without exposing credentials',()=>{const empty=gatewayRequirements({});assert.equal(empty.ready,false);assert.equal(empty.missing.length,4);const configured=gatewayRequirements({PF_GATEWAY_MODE:'test',PF_GATEWAY_USERNAME:'private-user',PF_GATEWAY_PASSWORD:'private-pass',PF_GATEWAY_SENDER_ID:'sender',PF_COMMUNICATION_EMAIL:'proof@example.dk'});assert.equal(configured.ready,true);assert.equal(configured.missing.length,0);assert.ok(!JSON.stringify(configured).includes('private-pass'));});
test('gateway accepts only a matching PF success response',async()=>{const env={PF_GATEWAY_MODE:'test',PF_GATEWAY_USERNAME:'u',PF_GATEWAY_PASSWORD:'p',PF_GATEWAY_SENDER_ID:'s',PF_COMMUNICATION_EMAIL:'x@y.dk'},payload=buildPFOrder(base,{...settings,isTest:true});const fetchImpl=async(url,options)=>{assert.match(url,/\/test\//);assert.match(options.headers.Authorization,/^Basic /);return {ok:true,status:202,json:async()=>({status:'success',yourMessageId:'message-1',message:'Order accepted.'})};};assert.equal((await submitPFOrder(payload,{env,fetchImpl})).httpStatus,202);await assert.rejects(submitPFOrder(payload,{env,fetchImpl:async()=>({ok:true,status:202,json:async()=>({status:'success',yourMessageId:'wrong'})})}),/afviste/);});
test('Gateway selects the password for the active environment',async()=>{const env={PF_GATEWAY_MODE:'test',PF_GATEWAY_USERNAME:'u',PF_GATEWAY_TEST_PASSWORD:'test-secret',PF_GATEWAY_PROD_PASSWORD:'prod-secret',PF_GATEWAY_SENDER_ID:'s',PF_COMMUNICATION_EMAIL:'x@y.dk'},payload=buildPFOrder(base,{...settings,isTest:true});const fetchImpl=async(url,options)=>{assert.equal(options.headers.Authorization,`Basic ${Buffer.from('u:test-secret').toString('base64')}`);return {ok:true,status:202,json:async()=>({status:'success',yourMessageId:'message-1'})};};await submitPFOrder(payload,{env,fetchImpl});});
test('protected Gateway test order is blank, fixed and unavailable outside test mode',()=>{const request={confirmation:'TEST',name:'Joakim',email:'joakim@example.dk',phone:'12345678',street:'Testvej 1',postalCode:'1000',city:'København'},input=gatewayTestOrderInput(request,{env:{PF_GATEWAY_MODE:'test'}});assert.deepEqual(input.lines,[{productId:'pf-38687',sku:'38687550',quantity:50,decorations:[]}]);assert.equal(input.shipping.address.street2,'PF TEST – MÅ IKKE PRODUCERES');assert.throws(()=>gatewayTestOrderInput({...request,confirmation:'test'},{env:{PF_GATEWAY_MODE:'test'}}),/Skriv TEST/);assert.throws(()=>gatewayTestOrderInput(request,{env:{PF_GATEWAY_MODE:'live'}}),/kun sendes/);});
