import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {rm} from 'node:fs/promises';
import {persistCheckout,readCheckout} from '../lib/checkout.mjs';
import {applyQuickpayCallback,captureQuickpay,createQuickpayLink,quickpayPaymentState,verifyQuickpayCallback} from '../lib/quickpay.mjs';

const env={PAYMENT_PROVIDER:'quickpay',QUICKPAY_API_KEY:'test-key',QUICKPAY_PRIVATE_KEY:'private-key',QUICKPAY_AUTH_HOLD_HOURS:'48',SMERCH_PUBLIC_BASE_URL:'http://localhost:5173',SMERCH_FREIGHT_EX_VAT_DKK:'40'};
const response=data=>({ok:true,json:async()=>data});
test('Quickpay link reserves without auto capture and signed callback controls order state',async()=>{const id=`pay-${randomUUID()}`,order={id,paymentProvider:'quickpay',status:'prepared',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),totalIncVat:10000,paymentAttempt:0,shipping:{email:'test@example.dk'},pfOrderIds:[],events:[]};await persistCheckout(order);let paymentId,linkBody,captureCalls=0;const authorized=()=>({id:12345,order_id:paymentId,currency:'DKK',type:'Payment',link:{amount:10000},accepted:true,operations:[{id:1,type:'authorize',amount:10000,pending:false,qp_status_code:'20000',created_at:new Date().toISOString()}]});try{const session=await createQuickpayLink(id,{env,fetchImpl:async(url,options)=>{if(options.method==='POST'&&url.endsWith('/payments')){paymentId=JSON.parse(options.body).order_id;return response({id:12345,order_id:paymentId});}if(options.method==='PUT'){linkBody=JSON.parse(options.body);return response({url:'https://payment.quickpay.net/payments/test-link'});}throw Error(url);}});assert.equal(session.paymentId,12345);assert.equal(linkBody.amount,10000);assert.equal(linkBody.auto_capture,false);assert.equal(linkBody.callback_url,'http://localhost:5173/api/quickpay/callback');assert.equal((await readCheckout(id)).status,'awaiting_payment');const raw=Buffer.from(JSON.stringify(authorized())),sig=createHmac('sha256',env.QUICKPAY_PRIVATE_KEY).update(raw).digest('hex');assert.equal(verifyQuickpayCallback(raw,sig,env.QUICKPAY_PRIVATE_KEY),true);assert.equal(verifyQuickpayCallback(Buffer.from('wrong'),sig,env.QUICKPAY_PRIVATE_KEY),false);assert.equal(quickpayPaymentState({...authorized(),link:{amount:1}},10000),'invalid');await applyQuickpayCallback(authorized(),{env});await applyQuickpayCallback(authorized(),{env});assert.equal((await readCheckout(id)).status,'authorized');const fetchImpl=async(url,options)=>{if(options.method==='POST'){captureCalls++;const payment=authorized();payment.operations.push({id:2,type:'capture',amount:10000,pending:false,qp_status_code:'20000'});return response(payment);}return response(authorized());};await assert.rejects(captureQuickpay(id,{env,fetchImpl,canCapture:async()=>false}),/ikke godkendt/);assert.equal(captureCalls,0);await captureQuickpay(id,{env,fetchImpl,canCapture:async()=>true});assert.equal(captureCalls,1);assert.equal((await readCheckout(id)).status,'paid');}finally{await rm(new URL(`../.private/checkouts/${id}.json`,import.meta.url),{force:true});}});

test('Quickpay capture never posts after the conservative authorization window',async()=>{const id=`pay-${randomUUID()}`,orderId='SM123456789012340000',order={id,paymentProvider:'quickpay',status:'authorized',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),authorizedAt:new Date(Date.now()-7200000).toISOString(),authorizationExpiresAt:new Date(Date.now()-3600000).toISOString(),totalIncVat:10000,quickpayPaymentId:12345,quickpayOrderId:orderId,pfOrderIds:[],events:[]};await persistCheckout(order);let posts=0;try{await assert.rejects(captureQuickpay(id,{env,canCapture:async()=>true,fetchImpl:async(url,options)=>{if(options.method==='POST')posts++;return response({id:12345,order_id:orderId,currency:'DKK',type:'Payment',link:{amount:10000},accepted:true,operations:[{id:1,type:'authorize',amount:10000,pending:false,qp_status_code:'20000'}]});}}),/udløbet/);assert.equal(posts,0);assert.equal((await readCheckout(id)).status,'authorization_expired');}finally{await rm(new URL(`../.private/checkouts/${id}.json`,import.meta.url),{force:true});}});
