import { brands } from './brands.mjs';
import { publicProduct } from './providers.mjs';
// Demo provider. No supplier credentials or commercial data are configured.
const a = name => `/assets/${name}`;
const garment = (prefix, color, hex) => ({name:color,hex,images:[a(`${prefix}-front.jpg`),a(`${prefix}-back.jpg`)]});
const textilePrint = [{id:'transfer',name:'Transfertryk',positions:['Venstre bryst','Forside','Ryg'],unit:12,setup:250},{id:'embroidery',name:'Broderi',positions:['Venstre bryst'],unit:25,setup:450}];
const raw = [
 {id:'classic-tee',name:'Classic T-shirt',category:'toj',material:'Bomuld',brand:'Tekstil-demo',description:'En enkel T-shirt med rund hals. Prøv farver, størrelsesfordeling og placering af dit logo.',colors:[garment('russell-white','Hvid','#ffffff'),garment('russell-black','Sort','#222222')],sizes:['S','M','L','XL','XXL'],minimum:25,price:65,prints:textilePrint},
 {id:'everyday-hoodie',name:'Everyday Hoodie',category:'toj',material:'Bomuldsblanding',brand:'Tekstil-demo',description:'Hættetrøjen til holdet, hverdagen og de kølige aftener. Sammensæt en vejledende forespørgsel med dit eget logo.',colors:[garment('russell-basic-hoodie-bright-royal','Blå','#2445b8'),garment('russell-basic-hoodie-black','Sort','#222222')],sizes:['S','M','L','XL','XXL'],minimum:25,price:185,prints:textilePrint},
 {id:'crew-sweat',name:'Studio Sweatshirt',category:'toj',material:'Bomuldsblanding',brand:'Tekstil-demo',description:'En sweatshirt med rund hals og et afslappet udtryk. Et eksempel på merchandise til medarbejdere og events.',colors:[garment('russell-authentic-sweat-indigo-blue','Blå','#536581')],sizes:['S','M','L','XL'],minimum:25,price:145,prints:textilePrint},
 {id:'canvas-tote',name:'Canvas Tote',category:'tasker',material:'Bomuld',brand:'Merch-demo',description:'En rummelig mulepose med plads til hverdagens ting og dit budskab. Billedet er en genereret illustration af demoproduktet.',colors:[{name:'Natur',hex:'#d5c8b5',images:[a('tote.jpg')]}],minimum:50,price:32,prints:[{id:'screen',name:'Serigrafi · 1 farve',positions:['Forside','Bagside'],unit:8,setup:300}]},
 {id:'thermal-bottle',name:'Daily Termoflaske',category:'flasker',material:'Rustfrit stål',brand:'Merch-demo',description:'En termoflaske med et enkelt udtryk. Billedet er en genereret illustration; mål, kapacitet og specifikationer afklares i det endelige sortiment.',colors:[{name:'Navy',hex:'#16233a',images:[a('bottle.jpg')]}],minimum:25,price:85,prints:[{id:'laser',name:'Lasergravering',positions:['Forside'],unit:15,setup:200}]},
 {id:'event-kit',name:'Eventpakken',category:'gaver',material:'Blandede materialer',brand:'Merch-demo',description:'Saml tekstiler og merchandise til dit næste event. Pakkens indhold og pris aftales individuelt. Billedet viser inspiration, ikke et fast pakkeindhold.',colors:[{name:'Efter aftale',hex:'#4969e9',images:[a('hero.jpg')]}],minimum:25,price:null,prints:[{id:'custom',name:'Tilpasses efter aftale',positions:['Efter aftale'],unit:null,setup:null}]},
 {id:'flyer',name:'Flyers',category:'tryksager',material:'Papir',brand:'Egne tryksager',description:'Et budskab, man kan tage med. Vælg format, papir og antal til din forespørgsel. Grafikken er et eksempel på layout.',art:'flyer',colors:[{name:'Fuld farve',hex:'#2445b8',images:[]}],minimum:100,price:null,prints:[{id:'digital',name:'Digitaltryk',positions:['Begge sider','Forside'],unit:null,setup:null}],options:{Format:['A6','A5','A4'],Papir:['170 g bestrøget','250 g bestrøget'],Efterbehandling:['Ingen','Mat laminering']}},
 {id:'poster',name:'Plakater',category:'tryksager',material:'Papir',brand:'Egne tryksager',description:'Giv arrangementet eller kampagnen plads. Vælg dine ønsker, og få materialer og endelig pris bekræftet i et tilbud.',art:'poster',colors:[{name:'Fuld farve',hex:'#f07045',images:[]}],minimum:10,price:null,prints:[{id:'digital',name:'Digitaltryk',positions:['Forside'],unit:null,setup:null}],options:{Format:['A3','A2','A1'],Papir:['170 g bestrøget','200 g mat'],Efterbehandling:['Ingen']}},
 {id:'cards',name:'Visitkort',category:'kontor',material:'Papir',brand:'Egne tryksager',description:'Et lille format til en god introduktion. Vælg papir og finish; endelige specifikationer og pris afklares i tilbuddet.',art:'cards',colors:[{name:'Fuld farve',hex:'#2445b8',images:[]}],minimum:100,price:null,prints:[{id:'digital',name:'Digitaltryk',positions:['Begge sider','Forside'],unit:null,setup:null}],options:{Format:['85 × 55 mm'],Papir:['350 g ubestrøget','400 g bestrøget'],Efterbehandling:['Ingen','Mat laminering']}}
];
export const categories = [{id:'toj',name:'Tøj og tekstiler'},{id:'tasker',name:'Tasker'},{id:'flasker',name:'Flasker og krus'},{id:'kontor',name:'Kontor og reklameartikler'},{id:'gaver',name:'Gaver og events'},{id:'tryksager',name:'Tryksager'}];
export const products = raw.map((p,index)=>({...p,demo:true,sku:`DEMO-${String(index+1).padStart(3,'0')}`,supplier:{id:p.brand==='Egne tryksager'?'own-demo':'demo',productId:p.id},certifications:[],stock:{status:'unknown',updatedAt:null},leadTime:null,sizes:p.sizes||['Standard'],tiers:p.price===null?[]:[{min:p.minimum,unit:p.price},{min:100,unit:Math.round(p.price*.9)},{min:250,unit:Math.round(p.price*.8)}],variants:p.colors.flatMap((c,ci)=>(p.sizes||['Standard']).map(size=>({sku:`DEMO-${index+1}-${ci}-${size}`,color:c.name,size,status:'active'}))),status:'active'}));
export function publicCatalog(){return {source:'demo',updatedAt:null,categories,brands,products:products.map(publicProduct)};}
