import {readFile} from 'node:fs/promises';
import {MARKETING_VERSION,marketingConsent} from '../dist/legal-consent.mjs';
export const legalPaths=new Set(['/handelsbetingelser','/privatlivspolitik','/fortryd-aftale','/marketing']);
export async function legalPage(path,params){
 const lang=params.get('lang')==='en'?'en':'da',en=lang==='en',withdraw=path==='/fortryd-aftale',marketing=path==='/marketing',unsubscribe=params.get('mode')==='unsubscribe';
 const labels=en?['Terms and conditions','Privacy policy','Withdraw from contract','Marketing preferences']:['Handelsbetingelser','Privatlivspolitik','Fortryd aftale','Marketingvalg'];
 const title=labels[[...legalPaths].indexOf(path)];let body;
 if(!withdraw&&!marketing)body=await readFile(new URL(`../dist/legal/${path==='/handelsbetingelser'?'terms':'privacy'}-${lang}.html`,import.meta.url),'utf8');
 else if(withdraw)body=`<h1>${title}</h1><p>${en?'Use this form to notify us that you withdraw from a purchase. Personalised goods are generally exempt from withdrawal; rights concerning defects remain unaffected.':'Brug formularen til at meddele, at du fortryder et køb. Personligt tilpassede varer er som udgangspunkt undtaget fra fortrydelsesretten. Reklamationsretten berøres ikke.'}</p><form data-legal-form="withdrawal"><label>${en?'Name':'Navn'}<input name="name" required maxlength="120" autocomplete="name"></label><label>E-mail<input name="email" type="email" required maxlength="254" autocomplete="email"></label><label>${en?'Order reference':'Ordreference'}<input name="orderReference" required maxlength="160"></label><label>${en?'Goods (leave empty for the whole order)':'Varer (lad stå tomt for hele ordren)'}<textarea name="items" maxlength="1000"></textarea></label><p>${en?'We record the time of your notice and provide a receipt you can save. A receipt is also sent by email; if email is temporarily unavailable, it is queued.':'Vi registrerer tidspunktet og giver dig en kvittering, du kan gemme. Kvitteringen sendes også på e-mail; ved midlertidig mailfejl sættes den i kø.'}</p><label class="check"><input type="checkbox" name="confirmed" required>${en?'I hereby withdraw from the contract identified above.':'Jeg meddeler hermed, at jeg fortryder den ovenfor angivne aftale.'}</label><button type="submit">${en?'Confirm withdrawal':'Bekræft fortrydelse'}</button><p role="status" class="form-status"></p></form><div id="receipt"></div>`;
 else body=`<h1>${unsubscribe?(en?'Unsubscribe from marketing':'Afmeld marketing'):(en?'Offers and inspiration from Smerch':'Tilbud og inspiration fra Smerch')}</h1><p>${en?'Signing up is optional and does not affect purchases or customer service. You can unsubscribe free of charge at any time.':'Tilmelding er frivillig og påvirker ikke køb eller kundeservice. Du kan altid afmelde dig gratis.'}</p><form data-legal-form="${unsubscribe?'unsubscribe':'subscribe'}"><label>E-mail<input name="emailAddress" type="email" maxlength="254" autocomplete="email"></label><label>${en?'Phone (country code, e.g. +45)':'Telefon (landekode, fx +45)'}<input name="phone" type="tel" maxlength="40" autocomplete="tel"></label>${unsubscribe?`<p>${en?'Enter the email address and/or number you want removed from marketing. Your order is unaffected.':'Angiv den e-mailadresse og/eller det nummer, du vil afmelde. Det påvirker ikke din ordre.'}</p>`:`<fieldset><legend>${en?'Choose channels':'Vælg kanaler'}</legend>${Object.entries(marketingConsent[lang]).map(([key,text])=>`<label class="check"><input type="checkbox" name="${key}">${text}</label>`).join('')}</fieldset><label class="check"><input type="checkbox" name="ownDetails" required>${en?'These are my own contact details.':'Det er mine egne kontaktoplysninger.'}</label><p>${en?'Consent is given only when you press Sign up. No sales calls or marketing from other companies are included.':'Samtykket gives først, når du trykker Tilmeld. Det omfatter ikke salgsopkald eller marketing fra andre virksomheder.'}</p>`}<button type="submit">${unsubscribe?(en?'Unsubscribe':'Afmeld'):(en?'Sign up':'Tilmeld')}</button><p role="status" class="form-status"></p></form><p><a href="/marketing?${unsubscribe?'':'mode=unsubscribe&'}lang=${lang}">${unsubscribe?(en?'Go to signup':'Gå til tilmelding'):(en?'Unsubscribe instead':'Afmeld i stedet')}</a></p>`;
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="strict-origin-when-cross-origin"><title>${title} | Smerch</title><link rel="stylesheet" href="/legal.css"><script type="module" src="/legal-client.mjs"></script></head><body data-locale="${lang}" data-consent-version="${MARKETING_VERSION}"><header><a href="/"><span class="legal-brand">Smerch</span></a><nav aria-label="Language"><a href="${path}?${unsubscribe?'mode=unsubscribe&':''}lang=da" ${!en?'aria-current="true"':''}>DA</a><a href="${path}?${unsubscribe?'mode=unsubscribe&':''}lang=en" ${en?'aria-current="true"':''}>EN</a></nav></header><main>${body}${withdraw||marketing?`<p class="small">${en?'Read how we use your information in our':'Læs om brug af dine oplysninger i vores'} <a href="/privatlivspolitik?lang=${lang}">${labels[1]}</a>.</p>`:''}</main><footer><nav>${[...legalPaths].map((p,i)=>`<a href="${p}?lang=${lang}">${labels[i]}</a>`).join('')}</nav><p>Trykeksperten ApS · CVR 44015773 · Raffinaderivej 20, 2300 København S<br><a href="mailto:hello@smerch.dk">hello@smerch.dk</a> · <a href="tel:+4527822277">+45 27 82 22 77</a></p></footer></body></html>`;
}
