import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {checkoutConfiguration,listCheckouts,readCheckout,updateCheckout} from './checkout.mjs';

const base='https://api.quickpay.net';
const paymentOrderId=(id,attempt=0)=>`SM${createHash('sha256').update(id).digest('hex').slice(0,14)}${String(attempt).padStart(4,'0')}`;
const successful=operation=>operation&&!operation.pending&&String(operation.qp_status_code)==='20000';
const last=(payment,type)=>(payment.operations||[]).filter(operation=>operation.type===type).at(-1);
const errorText=(data,fallback)=>String(data?.message||data?.error||fallback).slice(0,180);
function headers(env){return {Authorization:`Basic ${Buffer.from(`:${env.QUICKPAY_API_KEY}`).toString('base64')}`,'Accept-Version':'v10','Content-Type':'application/json'};}
async function request(path,{method='GET',body,env=process.env,fetchImpl=fetch}={}){const response=await fetchImpl(`${base}${path}`,{method,headers:headers(env),body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw Error(errorText(result,`Quickpay svarede ${response.status}.`));return result;}
export function verifyQuickpayCallback(raw,header,privateKey){if(!Buffer.isBuffer(raw)||!privateKey||!/^[a-f0-9]{64}$/i.test(String(header||'')))return false;return timingSafeEqual(createHmac('sha256',privateKey).update(raw).digest(),Buffer.from(header,'hex'));}
export function quickpayPaymentState(payment,expectedAmount){
 if(payment?.type!=='Payment'||String(payment.currency).toUpperCase()!=='DKK'||Number(payment.link?.amount)!==expectedAmount)return 'invalid';
 const authorization=last(payment,'authorize'),capture=last(payment,'capture'),cancel=last(payment,'cancel');
 if(successful(capture)&&capture.amount===expectedAmount)return 'paid';
 if(successful(cancel)&&(!capture||Number(cancel.id)>Number(capture.id)))return 'cancelled';
 if(successful(authorization)&&authorization.amount===expectedAmount&&payment.accepted===true)return 'authorized';
 if(authorization&&!successful(authorization))return authorization.pending?'pending':'failed';
 return 'pending';
}
export async function createQuickpayLink(id,{env=process.env,fetchImpl=fetch}={}){
 const order=await readCheckout(id),config=checkoutConfiguration({...env,PAYMENT_PROVIDER:'quickpay'});if(order.paymentProvider!=='quickpay'||!config.ready)throw Error(config.reason||'Quickpay er ikke valgt.');if(!['prepared','payment_setup','authorization_expired','expired','payment_failed'].includes(order.status))throw Error('Betalingen kan ikke startes igen.');
 const attempt=order.paymentAttempt||0,qpOrderId=paymentOrderId(id,attempt),url=new URL(env.SMERCH_PUBLIC_BASE_URL).origin;
 let paymentId=order.quickpayPaymentId;
 if(!paymentId){await updateCheckout(id,current=>{current.status='payment_setup';current.quickpayOrderId=qpOrderId;return current;});let payment;try{payment=await request('/payments',{method:'POST',body:{order_id:qpOrderId,currency:'DKK'},env,fetchImpl});}catch(error){await updateCheckout(id,current=>{current.status='payment_setup_uncertain';current.events.push({at:new Date().toISOString(),type:'quickpay_create_uncertain',message:error.message});return current;});throw Error('Quickpay-betalingen kræver afstemning før nyt forsøg.');}if(!Number.isSafeInteger(payment.id)||payment.order_id!==qpOrderId)throw Error('Quickpay returnerede ikke et entydigt betalings-id.');paymentId=payment.id;await updateCheckout(id,current=>{current.quickpayPaymentId=paymentId;current.quickpayOrderId=qpOrderId;return current;});}
 const link=await request(`/payments/${paymentId}/link`,{method:'PUT',body:{amount:order.totalIncVat,language:'da',auto_capture:false,auto_fee:false,payment_methods:env.QUICKPAY_PAYMENT_METHODS||'mobilepay,apple-pay,creditcard',continue_url:`${url}/ordre?checkout=${encodeURIComponent(id)}`,cancel_url:`${url}/betaling?annulleret=1`,callback_url:`${url}/api/quickpay/callback`,customer_email:order.shipping.email},env,fetchImpl});
 if(!/^https:\/\/payment\.quickpay\.net\/payments\//.test(link.url||''))throw Error('Quickpay returnerede ikke et sikkert betalingslink.');
 await updateCheckout(id,current=>{current.status='awaiting_payment';current.quickpayLinkUrl=link.url;current.events.push({at:new Date().toISOString(),type:'quickpay_link_created',paymentId});return current;});return {id,paymentId,url:link.url};
}
export async function applyQuickpayCallback(payment,{env=process.env}={}){const order=(await listCheckouts()).find(row=>row.paymentProvider==='quickpay'&&row.quickpayOrderId===payment.order_id&&row.quickpayPaymentId===payment.id);if(!order)return null;return updateCheckout(order.id,current=>{
 if(current.quickpayPaymentId!==payment.id||current.quickpayOrderId!==payment.order_id)throw Error('Quickpay-betalingen matcher ikke ordren.');const state=quickpayPaymentState(payment,current.totalIncVat);if(state==='invalid')throw Error('Quickpay-beløb eller valuta matcher ikke ordren.');const operation=payment.operations?.at(-1),key=operation?`quickpay-${payment.id}-${operation.id}`:null;if(key&&current.events.some(event=>event.id===key))return current;
 const at=new Date().toISOString();if(state==='paid'){current.status='paid';current.paidAt=at;}else if(state==='authorized'&&current.status==='cancelled')current.status='needs_attention';else if(state==='authorized'&&['awaiting_payment','payment_setup','authorized'].includes(current.status)){current.status='authorized';current.authorizedAt=current.authorizedAt||at;const hours=Number(env.QUICKPAY_AUTH_HOLD_HOURS||24),authorizedAt=Date.parse(last(payment,'authorize')?.created_at||at);if(!current.authorizationExpiresAt&&hours>0&&hours<=168&&Number.isFinite(authorizedAt))current.authorizationExpiresAt=new Date(authorizedAt+hours*3600000).toISOString();}else if(state==='cancelled'&&!['paid','cancelled'].includes(current.status))current.status='authorization_expired';else if(state==='failed'&&current.status==='awaiting_payment')current.status='payment_failed';if(key)current.events.push({id:key,at,type:`quickpay_${state}`});return current;
 });}
export async function getQuickpayPayment(order,{env=process.env,fetchImpl=fetch}={}){if(!Number.isSafeInteger(order.quickpayPaymentId))throw Error('Quickpay-betalingsnummer mangler.');const payment=await request(`/payments/${order.quickpayPaymentId}`,{env,fetchImpl});if(payment.id!==order.quickpayPaymentId||payment.order_id!==order.quickpayOrderId||quickpayPaymentState(payment,order.totalIncVat)==='invalid')throw Error('Quickpay-betalingen matcher ikke ordren.');return payment;}
export async function captureQuickpay(id,{env=process.env,fetchImpl=fetch,canCapture=async()=>true,now=Date.now()}={}){
 const order=await readCheckout(id);if(order.status==='paid')return order;if(order.status!=='authorized'&&order.status!=='capture_reconciliation')throw Error('Ordren har ingen aktiv reservation.');if(!await canCapture(order))throw Error('Den seneste korrektur er ikke godkendt for alle PF-ordrer.');const payment=await getQuickpayPayment(order,{env,fetchImpl}),state=quickpayPaymentState(payment,order.totalIncVat);if(state==='paid'){return updateCheckout(id,current=>{current.status='paid';current.paidAt=current.paidAt||new Date(now).toISOString();return current;});}if(order.status==='capture_reconciliation')throw Error('Hævningen skal afstemmes hos Quickpay før et nyt kald.');if(state!=='authorized'||!order.authorizationExpiresAt||Date.parse(order.authorizationExpiresAt)<=now+60000){await updateCheckout(id,current=>{current.status='authorization_expired';return current;});throw Error('Reservationen er udløbet eller dækker ikke ordren. Kunden skal godkende betaling igen.');}
 await updateCheckout(id,current=>{current.status='capture_reconciliation';current.events.push({at:new Date().toISOString(),type:'quickpay_capture_requested'});return current;});let result;try{result=await request(`/payments/${payment.id}/capture`,{method:'POST',body:{amount:order.totalIncVat},env,fetchImpl});}catch(error){throw Error(`Hævningen kræver afstemning hos Quickpay: ${error.message}`);}if(quickpayPaymentState(result,order.totalIncVat)!=='paid')throw Error('Hævningen afventer Quickpay-kvittering og skal afstemmes.');return updateCheckout(id,current=>{current.status='paid';current.paidAt=new Date().toISOString();current.events.push({at:current.paidAt,type:'quickpay_captured'});return current;});
}
export async function cancelQuickpay(id,{env=process.env,fetchImpl=fetch}={}){const order=await readCheckout(id);if(order.status==='cancelled')return order;if(['paid','capture_reconciliation'].includes(order.status))throw Error('Hævet eller uafklaret betaling kræver manuel afstemning.');if(order.quickpayPaymentId){const payment=await getQuickpayPayment(order,{env,fetchImpl}),state=quickpayPaymentState(payment,order.totalIncVat);if(state==='paid')throw Error('Quickpay-betalingen er allerede hævet.');if(state==='pending')throw Error('Betalingslinket kan stadig bruges. Afklar eller luk det hos Quickpay før annullering.');if(state==='authorized'){const result=await request(`/payments/${payment.id}/cancel`,{method:'POST',body:{},env,fetchImpl});if(quickpayPaymentState(result,order.totalIncVat)!=='cancelled')throw Error('Quickpay-annulleringen kræver afstemning.');}}return updateCheckout(id,current=>{current.status='cancelled';current.events.push({at:new Date().toISOString(),type:'cancelled',pfCancellationRequired:Boolean(current.pfOrderIds?.length)});return current;});}
export async function renewQuickpay(id,{env=process.env,fetchImpl=fetch,validate=async()=>{}}={}){const order=await readCheckout(id);if(!['authorization_expired','expired','payment_failed'].includes(order.status))throw Error('Ordren er ikke klar til ny reservation.');await validate(order);if(order.quickpayPaymentId){const payment=await getQuickpayPayment(order,{env,fetchImpl}),state=quickpayPaymentState(payment,order.totalIncVat);if(state==='paid')throw Error('Betalingen er allerede hævet og skal afstemmes.');if(['pending','failed'].includes(state)){if(!order.quickpayLinkUrl)throw Error('Quickpay-linket skal afstemmes før nyt forsøg.');await updateCheckout(id,current=>{current.status='awaiting_payment';return current;});return {id,paymentId:order.quickpayPaymentId,url:order.quickpayLinkUrl};}if(state==='authorized'){const result=await request(`/payments/${payment.id}/cancel`,{method:'POST',body:{},env,fetchImpl});if(quickpayPaymentState(result,order.totalIncVat)!=='cancelled')throw Error('Den gamle reservation kunne ikke frigives.');}}await updateCheckout(id,current=>{current.previousQuickpayPaymentIds=[...(current.previousQuickpayPaymentIds||[]),current.quickpayPaymentId].filter(Boolean);current.paymentAttempt=(current.paymentAttempt||0)+1;current.quickpayPaymentId=null;current.quickpayOrderId=null;current.quickpayLinkUrl=null;current.authorizedAt=null;current.authorizationExpiresAt=null;current.status='prepared';return current;});return createQuickpayLink(id,{env,fetchImpl});}
